# Generated by Django 3.2.5 on 2021-09-21 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='badges',
        ),
        migrations.RemoveField(
            model_name='student',
            name='points',
        ),
        migrations.RemoveField(
            model_name='student',
            name='resource_rating',
        ),
    ]
