# Generated by Django 3.2.5 on 2021-09-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210921_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='badges',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='resource_rating',
            field=models.TextField(null=True),
        ),
    ]
