# Generated by Django 3.2.5 on 2022-01-06 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20220106_1738'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scholarship',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
