# Generated by Django 3.2.5 on 2022-02-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_resourcelink_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcelink',
            name='rating',
            field=models.TextField(default='{}', null=True),
        ),
    ]
