# Generated by Django 3.2.5 on 2022-02-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_friends_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default='hello', max_length=100),
            preserve_default=False,
        ),
    ]
