# Generated by Django 3.2.5 on 2022-02-23 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_student_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='badges',
        ),
    ]
