# Generated by Django 3.2.5 on 2022-02-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.CharField(default=6, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='nk_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
